// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAac5gA3LN9avyZci5NbOrICJezG9ocBrc',
    appId: '1:52194306568:web:c7665d294350e367ce3fbd',
    messagingSenderId: '52194306568',
    projectId: 'apk-scanner-f00c7',
    authDomain: 'apk-scanner-f00c7.firebaseapp.com',
    storageBucket: 'apk-scanner-f00c7.firebasestorage.app',
    measurementId: 'G-WXWPZV8TMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTyJY0sd6G6ErepMZd-ySNjleGrFYPbh4',
    appId: '1:52194306568:android:91047c8729f79b10ce3fbd',
    messagingSenderId: '52194306568',
    projectId: 'apk-scanner-f00c7',
    storageBucket: 'apk-scanner-f00c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKAt03S7kMcdcWxBrP7ce1vUYy7qUTJuo',
    appId: '1:52194306568:ios:33fb71c32c994061ce3fbd',
    messagingSenderId: '52194306568',
    projectId: 'apk-scanner-f00c7',
    storageBucket: 'apk-scanner-f00c7.firebasestorage.app',
    iosBundleId: 'com.example.apkScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKAt03S7kMcdcWxBrP7ce1vUYy7qUTJuo',
    appId: '1:52194306568:ios:33fb71c32c994061ce3fbd',
    messagingSenderId: '52194306568',
    projectId: 'apk-scanner-f00c7',
    storageBucket: 'apk-scanner-f00c7.firebasestorage.app',
    iosBundleId: 'com.example.apkScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAac5gA3LN9avyZci5NbOrICJezG9ocBrc',
    appId: '1:52194306568:web:9403abebbdda7c0cce3fbd',
    messagingSenderId: '52194306568',
    projectId: 'apk-scanner-f00c7',
    authDomain: 'apk-scanner-f00c7.firebaseapp.com',
    storageBucket: 'apk-scanner-f00c7.firebasestorage.app',
    measurementId: 'G-L2XDK1NN4N',
  );
}
